<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Support\Arabic;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds real student internship reviews from the College of Computing
 * "تجارب التدريب — كليه الحاسب" Google Form (2019-2021), 218 raw rows.
 *
 * Source: temp/تجارب التدريب - كليه الحاسب - Original Form responses.csv
 * SOURCE  = 'college_2019'
 *
 * Curation rules applied manually to each row:
 *  - SKIP the 2 placeholder rows at the top.
 *  - SKIP junk rows: empty / single-dot / single-letter companies or
 *    reviews < 20 real characters (~34 rows).
 *  - SKIP rows with no explicit modality signal (the free-form text
 *    must mention حضوري / دوام / مقر / city office / عن بعد / online /
 *    هجين etc.).  Guessing modality is forbidden per the spec.
 *  - Ratings (1..5) are inferred from review tone — the form has no
 *    numeric column, and the spec explicitly allows this.
 *  - mixed_env / job_offer / stipend_sar come directly from form columns
 *    and are null when the responder wrote "لا يوجد" / empty.
 *  - duration_months parsed from the free-form "مدة التدريب" column.
 *  - recommendation derived from overall_rating (>=4 yes, =3 maybe, <=2 no).
 *
 * Idempotency:
 *  This seeder is NOT fully idempotent (re-runs may create extra rating rows
 *  if migrations were not refreshed).  To stay safe on re-run we delete any
 *  existing rating that matches (company_id, first 120 chars of review_text)
 *  before re-inserting this seeder's rows.  For a clean slate, prefer
 *  `php artisan migrate:fresh --seed`.
 */
class CollegeExperiences2019Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $inserted = 0;
            $createdCompanies = 0;

            foreach ($this->rows() as $row) {
                $company = Company::firstOrCreate(
                    ['name_normalized' => Arabic::normalize($row['company'])],
                    ['name' => $row['company'], 'status' => 'approved'],
                );

                if ($company->wasRecentlyCreated) {
                    $createdCompanies++;
                }

                $fingerprint = mb_substr($row['review_text'], 0, 120);

                // Drop any prior copy of this exact review so the seeder can
                // be re-run safely without producing duplicates.
                DB::table('ratings')
                    ->where('company_id', $company->id)
                    ->where('review_text', 'like', $fingerprint.'%')
                    ->delete();

                DB::table('ratings')->insert([
                    'company_id' => $company->id,
                    'role_title' => $row['role_title'],
                    'department' => $row['department'] ?? null,
                    'city' => $row['city'] ?? null,
                    'duration_months' => $row['duration_months'],
                    'sector' => $row['sector'] ?? null,
                    'modality' => $row['modality'],
                    'stipend_sar' => $row['stipend_sar'] ?? null,
                    'had_supervisor' => $row['had_supervisor'] ?? null,
                    'mixed_env' => $row['mixed_env'] ?? null,
                    'job_offer' => $row['job_offer'] ?? null,
                    'rating_mentorship' => $row['rating_mentorship'],
                    'rating_learning' => $row['rating_learning'],
                    'rating_culture' => $row['rating_culture'],
                    'rating_compensation' => $row['rating_compensation'],
                    'overall_rating' => $row['overall_rating'],
                    'recommendation' => $row['recommendation'],
                    'review_text' => $row['review_text'],
                    'pros' => $row['pros'] ?? null,
                    'cons' => $row['cons'] ?? null,
                    'reviewer_name' => null,
                    'reviewer_major' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                $inserted++;
            }

            $this->command?->info("CollegeExperiences2019Seeder: inserted {$inserted} ratings, created {$createdCompanies} new companies.");
        });
    }

    /**
     * Curated rows kept after manual review of the 218-row form.
     * Each entry carries an explicit modality signal found in the
     * review or notes text — rows without a signal were dropped.
     *
     * @return array<int, array<string, mixed>>
     */
    private function rows(): array
    {
        return [
            // idx=9 — Leen (explicit: "في مكان خاص بالنساء" — physical office; positive tone)
            [
                'company' => 'لين لخدمات الأعمال',
                'role_title' => 'مطور تطبيقات',
                'department' => 'Technology / Development',
                'city' => null,
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'كان تدريبي تدريب تعاوني كمطور تطبيقات، تدربت بـ technology team. بداية تدريبي كان كله بال infrastructure and Unix command، بعده كانت مشاريع بسيطه. أغلب تدريبي كان بال development team على تقنيات اخترتها ( React.js, React Native, Android studio ). سويت معاهم مشروعين، أحدهما request change على android app والثاني مشروع جديد اشتغلت عليه أنا واثنين. من الأشياء اللي حبيتها بالفريق خلوني التزم ب GitHub واتعلمت أهمية ال command line. بنص التدريب أخذت أسبوع ونص مع ال quality team. أتيح لي قراءة ال BRD والتعامل مع customers. كانت تجربة تستحق الذكر.',
                'pros' => 'فريق داعم، تقنيات حديثة، التزام بـ GitHub',
                'cons' => null,
            ],

            // idx=23 — Elm information security (explicit: physical office, separate rooms)
            [
                'company' => 'شركة علم لأمن المعلومات',
                'role_title' => 'Android mobile application developer',
                'department' => 'علم سوفت',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 1000,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 3,
                'rating_compensation' => 2,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'القسم: علم سوفت، المسمى الوظيفي: android mobile application developer. المدرب: من خارج الشركة (CTO في شركة Superior ICT). المشاريع: Elm survey system، ومشروع من اختيارنا ديمو فقط. البيئة مختلطه في الممرات و قاعات الاجتماعات لكن المتدربات في مكتب خاص مع مدربات.',
                'pros' => null,
                'cons' => 'المدرب من خارج الشركة، مشروع ديمو فقط',
            ],

            // idx=27 — Dell EMC (explicit physical: "غرفه اجتماعات خارج المكاتب" "نقدر ندخل جوا المكاتب")
            [
                'company' => 'Dell EMC',
                'role_title' => 'متدرب تعاوني',
                'department' => 'Support',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 3,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'كان بقسم support. أغلب التدريب كان عبارة عن sessions يعلمونا أكثر من أننا نطبق. عرضوا علينا Demo لشغلهم وشرحوا لنا عن المسميات الوظيفية والستورجز والسيرفرز. عطونا كورس اسمه ISM والشهادة على الكورس نأخذها بأنفسنا إذا اجتزنا الاختبار. الموظفون متعاونون جدًا. علمونا كيف نخلي السيرة الذاتية كويسة وكيف نجاوب على أسئلة المقابلة. سوينا ٣ برزنتيشنز ومشروع بروجكت مانجمنت. المكان اللي كان فيه المتدربون كان غرفة اجتماعات خارج المكاتب، وإذا احتجنا نحاكي موظف نقدر ندخل جوا المكاتب.',
                'pros' => 'موظفون متعاونون، شهادة نهاية تدريب، تطوير السوفت سكيلز',
                'cons' => 'تدريب نظري أكثر من تطبيقي، بدون مكافأة',
            ],

            // idx=29 — Safe Decision (explicit: "فيه استراحة خاصة للنساء" — physical)
            [
                'company' => 'القرار الآمن - Safe Decision',
                'role_title' => 'متدرب Cybersecurity',
                'department' => 'SOC / Labs',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'تدريبي كان عن Cybersecurity والمسمى متدرب تدريب تعاوني. الخطة كانت تدريب على كل أقسام الشركة مع التركيز على المعمل ومركز العمليات الأمنية. كنا ٦ متدربين من جامعات مختلفة. بالبداية أخذنا كورسات مكثفة بالنتورك والسكيوريتي، ثم بدأنا العمل على شبكة خاصة فينا وسوينا لها installing and configuring وجربنا الـlogs. شاركنا بـ incident response وسوينا تقرير عنه. اشتغلنا على Miter-Lab مع أحد كبار المهندسين وراح يستخدمونه بالشركة. دخلت الـSOC وكانت تجربة جميلة. طلبوا منا تقارير متعددة. ما أذكر بيوم كنت فاضية. كان في ميتنقز اسبوعية مع الـCEO. الدوام مرن وفيه استراحة خاصة للنساء.',
                'pros' => 'خطة منظمة، مشاريع حقيقية، فريق متعاون، دوام مرن',
                'cons' => 'بدون مكافأة',
            ],

            // idx=36 — Riyadh Municipality (explicit: physical, "قسمونا ل٣ مجموعات" in office)
            [
                'company' => 'أمانة منطقة الرياض',
                'role_title' => 'مطور ويب',
                'department' => null,
                'city' => 'الرياض',
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'كنا ١٧ طالبة في التدريب، قسمونا ل٣ مجموعات كل مجموعة فيها ٥-٦ طالبات. كل مجموعة وكلت بمشروع تسويه وكنا مخيرين بين الويب سايت او آب. إحنا اخترنا الويب سايت وبديناه من الصفر وفي الأخير عرضناه لإدارة الأمانة. استمتعت بتدريبي، البنات كانوا لطيفات والمشرفة كانت تساعدنا قدر الإمكان.',
                'pros' => 'بيئة لطيفة، مشرفة داعمة، مشروع كامل',
                'cons' => 'بدون مكافأة',
            ],

            // idx=43 — STC Applications (explicit: physical offices, female section)
            [
                'company' => 'STC قطاع التطبيقات',
                'role_title' => 'متدرب',
                'department' => 'قطاع التطبيقات - CRM',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'تدربنا في قطاع التطبيقات بالخصوص على نظام CRM، هذا النظام أساسه من أوراكل وتم تطويره من قبل الاتصالات. اشتغلنا مع مطورين للنظام وأيضًا tester وتعمقنا بالتيستنق كثيرًا. فهمنا عمليات كثيرة كيف تتم من إصدار شرائح وتغيير ملكية وإضافة منتجات وكيف يضيفون ميزات جديدة للنظام. عملوا لنا سيشنز مختلفة بخصوص الاتصالات ككل والأمن المعلوماتي. المشرفات كانوا قمة بالأخلاق والتعامل. البيئة غير مختلطة لأن الجزء اللي تدربنا فيه ماسكينه بنات.',
                'pros' => 'مشرفات ممتازات، شغل على نظام إنتاجي حقيقي، تعلم عميق',
                'cons' => null,
            ],

            // idx=47 — Amanat Riyadh (explicit: separate building for women, physical)
            [
                'company' => 'امانة الرياض',
                'role_title' => 'System Analyst',
                'department' => null,
                'city' => 'الرياض',
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 2,
                'rating_learning' => 1,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 1,
                'recommendation' => 'no',
                'review_text' => 'سيستم اناليست - كان الوضع عازلين بنات التدريب بمبنى لحاله، كنا قروب خمس بنات ومعطينا مشروع خربوطي لويب سايت على مدى الشهرين نسويه مع حملة توعوية. صراحة اللي يبي شغل صح وتدريب على مستوى لا يفكر فيها. تحسفت مره أني تدربت فيها.',
                'pros' => null,
                'cons' => 'مشروع سطحي، لا يوجد تدريب فعلي',
            ],

            // idx=62 — Habib Hospital / Cloud Solutions (explicit: "كله رجال مافيه موظفات" physical)
            [
                'company' => 'مستشفى الحبيب - حلول السحابة',
                'role_title' => 'متدرب دعم فني',
                'department' => 'IT Support',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 1,
                'rating_learning' => 1,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 1,
                'recommendation' => 'no',
                'review_text' => 'تدربت في مستشفى الحبيب كان معي خمس بنات وحطونا بقسم شركة مشغله لهم (حلول السحابة). القسم كان عبارة عن دعم فني عن طريق الرد على اتصالات الموظفين ومعرفة المشاكل اللي تواجههم. طبعًا ما أعطونا يوزرات أو أجهزة، كنا مجرد نجلس بجانب الموظفين ونشوفهم يشتغلون. اللي يبي يستفيد من التدريب ما أنصحه. غير مستعدين للمتدربين وما عندهم خطة واضحة للتدريب. تدريبهم نظري ولا يوجد تطبيق عملي. القسم صغير جدًا وكله رجال مافيه موظفات إلا ثنتين والمكاتب جنب بعضها.',
                'pros' => null,
                'cons' => 'لا يوجد خطة، لا أجهزة للمتدربين، تدريب نظري',
            ],

            // idx=63 — RasMal (explicit remote: "كان الشغل عن بعد")
            [
                'company' => 'RasMal',
                'role_title' => 'متدرب تعاوني',
                'department' => null,
                'city' => null,
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'remote',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 2,
                'rating_learning' => 2,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 2,
                'recommendation' => 'no',
                'review_text' => 'كانوا Start-up يوم كنت اشتغل معهم والصراحة ما كان شغلهم احترافي أبدًا. كان الشغل عن بعد.',
                'pros' => null,
                'cons' => 'غير احترافيين',
            ],

            // idx=64 — Takaful (explicit remote: "الشغل كان اون لاين")
            [
                'company' => 'Takaful Charity Foundation',
                'role_title' => 'محلل بيانات',
                'department' => 'Data',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'nonprofit',
                'modality' => 'remote',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'Data Analysis — تدربت في قسم البيانات، الفريق اللي معي كان مكون من ثلاثة أشخاص، دكتور واثنين سينيور. ما اشتغلت على مشروع معين، التاسكات اللي كانت تجيني تعتمد على احتياج الشركة. بشكل عام تجربتي كانت متوسطة بحكم أن الشغل كان اون لاين فما دخلت مع التيم بشكل ممتاز، الأشخاص الموجودون كانوا متساعدين. تجربتي يمكن تكون مختلفة تمامًا بحكم أني تدربت اون لاين بسبب كورونا.',
                'pros' => 'أشخاص متساعدون',
                'cons' => 'اندماج محدود بسبب العمل عن بعد',
            ],

            // idx=70 — Aramco (explicit: "يسكنونهم في السكن الرئيسي" — physical Dhahran)
            [
                'company' => 'شركة ارامكو السعودية',
                'role_title' => 'متدرب تعاوني',
                'department' => 'نقل المعرفة',
                'city' => 'الظهران',
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3500,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 2,
                'rating_culture' => 5,
                'rating_compensation' => 5,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'تدربت في فريق التعلم التعاوني والتقنية يتبع لقسم نقل المعرفة. بداية أنت ما راح تشتغل على مشاريع حقيقية بحكم حساسية المعلومات وكونك مجرد متدرب، لذلك طريقتهم أنهم يبنون لك خطة تدريب بكورسات من نظام التعلم عندهم، وممكن تشتغل على مشروع جانبي مع المشرف. لا أنصح بالتدرب مع أرامكو لمن يطمع بالفائدة العملية والتطوير المهني، أنصحك فيها كتجربة لتطلع على بيئة عمل جميلة ومتنوعة وخصوصًا للبنات بحكم أنهم يسكنونهم في السكن الرئيسي.',
                'pros' => 'بيئة عمل جميلة، مكافأة جيدة، سكن للبنات',
                'cons' => 'شغل نظري، لا مشاريع حقيقية',
            ],

            // idx=71 — KAUH (explicit: separated offices, physical)
            [
                'company' => 'مستشفى الملك عبدالعزيز الجامعي',
                'role_title' => 'مطور ويب',
                'department' => 'إدارة تقنية المعلومات',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 3,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'تدربت في قسم إدارة تقنية المعلومات، ما في مسمى محدد لكن كنت ماسكة أشغال web development. التيم لطيف لكنه مشغول أغلب الوقت فما فيه الدعم الكافي للمتدربين. كنت المتدربة الوحيدة. الجهة لها عيوبها لكن أشوفها خيار مناسب لمن يبحث عن جهات غير مختلطة (مكاتب البنات مفصولة عن مكاتب العيال). كانوا يعطونني شغل على بروجكتس حقيقية، لكن شغلهم فوضوي. عرضوا علي أتطوع عندهم وكذلك طلبوا مني أقدم على وظيفة بمسمى إخصائي كمبيوتر.',
                'pros' => 'مشاريع حقيقية، بيئة غير مختلطة',
                'cons' => 'تيم مشغول، شغل فوضوي',
            ],

            // idx=73 — ANB (explicit: "يعيبه البعد كان في حي المربع" — physical location)
            [
                'company' => 'البنك العربي الوطني',
                'role_title' => 'متدرب أمن معلومات',
                'department' => 'Information Security',
                'city' => 'الرياض',
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'Information Security department. الإدارة كلها جديدة والستاف صغار وكلهم فاهمين شغلهم. البيئة جدًا مريحة. يعيبه البعد، كان في حي المربع. اشتغلت على data privacy and protection. لسه كل شي جديد فيه بس كنا مركزين على classification للتطبيقات والملفات.',
                'pros' => 'فريق فاهم، بيئة مريحة',
                'cons' => 'موقع بعيد، بدون مكافأة',
            ],

            // idx=75 — Masarat (explicit: "غرفة فيها انا وغرفة فيها موظفتين" — physical)
            [
                'company' => 'شركة مسارات العالمية',
                'role_title' => 'مطورة ويب',
                'department' => null,
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 3,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'كنت مطورة ويب، ما معي أحد بس أنا والمبرمج حقهم، خلوني أشتغل على موقعين للشركة. الشركة صغيرة، غرفة فيها أنا وغرفة فيها موظفتين وغرفة إدارة وغرفة للمبرمج. بالغرفة حقتي ما يدخلون رجال، ما يعتبر مختلط ولا نسائي. التجربة حلوة، تعلمت على .NET واستفدت ومرنين بساعات العمل. اللي يبحث عن تكوين علاقات وعمل كفريق ما تصلح له.',
                'pros' => 'تعلم .NET، دوام مرن، مشاريع حقيقية',
                'cons' => 'شركة صغيرة، عمل فردي',
            ],

            // idx=78 — MCIT (explicit: "ماياخذون اعداد كبيره اقصى عدد ٣ متدربين" — physical)
            [
                'company' => 'وزارة الاتصالات وتقنية المعلومات MCIT',
                'role_title' => 'متدرب أمن سيبراني',
                'department' => 'الأمن السيبراني',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'تدربت في الإدارة العامة للأمن السيبراني، خطتهم رائعة، طريقة تدريبهم rotation بين SOC و GRC، شهر هنا وشهر هناك وإذا تبين شهر زيادة تختارين أي قسم تتدربين فيه مع التيم. كانت فرصة عظيمة بالنسبة لي. ما يأخذون أعداد كبيرة، أقصى عدد ٣ متدربين ويعطونك حقك وأكثر، والتيم متعاونون جدًا والجميع بلا استثناء يحاول يساعدك. البيئة حلوة مرة.',
                'pros' => 'خطة rotation ممتازة، أعداد محدودة، فريق داعم',
                'cons' => 'بدون مكافأة',
            ],

            // idx=80 — UQU Network (explicit: "عملت ميدانيا في قسم الشبكة" — physical)
            [
                'company' => 'جامعة أم القرى العمادة التقنية',
                'role_title' => 'مهندس شبكات',
                'department' => 'الشبكات',
                'city' => 'مكة المكرمة',
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'مهندس شبكات. عملت ميدانيًا في قسم الشبكة بالعمادة مع الفنيين في إصلاح أعطال الشبكة في الحرم الجامعي، ثم عملت مع المهندسين في إعداد السوتشات وتحديثها.',
                'pros' => 'عمل ميداني حقيقي',
                'cons' => 'بدون مكافأة',
            ],

            // idx=83 — T2 (explicit: "تدريبي كان اونلاين")
            [
                'company' => 'T2',
                'role_title' => 'متدرب إدارة مشاريع',
                'department' => 'Project Management',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'private',
                'modality' => 'remote',
                'stipend_sar' => 500,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 2,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدريبي كان أونلاين. أول شيء كلموني وقالوا اختاري بين ثلاث مسارات (إدارة مشاريع، برمجة، قسم السيرفرات). سوو لنا اختبار بسيط عن المسار والمقابلة كانت أونلاين. القسم اللي تدربت فيه كان إدارة المشاريع PM. أول شهرين تقريبًا كانوا يعطونا زي المحاضرات، كل أسبوع أو أسبوعين يجينا موظف مختلف ويكلمنا عن أحد المواضيع (الكواليتي، التصميم، إدارة المشاريع، محلل البيانات). بعضهم كان يطلب مننا نطبق ونسلم وبعضهم زي الاساسمنت. وآخر شيء أخذوا متدربين من كل مسار وقسمونا ثلاث مجموعات وأعطونا مشروع. البيئة مختلطة كتجربتي أونلاين.',
                'pros' => 'جلسات متنوعة، مشروع جماعي',
                'cons' => 'مكافأة رمزية فقط',
            ],

            // idx=85 — KFMC (explicit: "التدريب كان عن بعد")
            [
                'company' => 'مدينة الملك فهد الطبية',
                'role_title' => 'متدرب',
                'department' => 'تقنية المعلومات - قسم تدريب الأنظمة',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'remote',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 3,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'المسمى الوظيفي متدرب. اسم الإدارة: الإدارة التنفيذية لتقنية المعلومات. اسم القسم: قسم تدريب الأنظمة. التدريب كان (عن بعد) من الساعة ٩ الصباح إلى ٤. التدريب عبارة عن دروس ومبادئ تساعد بالأخير أن ننشئ web application development باستخدام لغات عدة منها sql و C# و html وcss.',
                'pros' => null,
                'cons' => 'تدريب تعليمي أكثر من عملي',
            ],

            // idx=87 — Asaleeb Zakia (explicit: "التدريب اونلاين او عن بعد حسب الرغبة")
            [
                'company' => 'الاساليب الذكية',
                'role_title' => 'متدرب مسار القوى الكهربائية',
                'department' => null,
                'city' => null,
                'duration_months' => 3,
                'sector' => 'private',
                'modality' => 'remote',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'تدربت بمسار القوى الكهربائية والإلكترونيات، والمهمات كانت عبارة عن تكوين الدوائر الكهربائية والأردوينو. التدريب أونلاين أو عن بعد حسب الرغبة وكل مسار ينفذ مهام مختلفة للمشاركة بتجهيز مشروع واحد ضخم. ما كان التدريب صعب، فقط عبارة عن تعليم ذاتي ومستواه جيد حتى للمبتدئين. يستقبلون متدربين بجميع الأعمار. أنصحكم تأخذوه بسنة مختلفة عن تدريب الجامعة وتروحوا لمكان أفضل بسنة التدريب.',
                'pros' => 'مرونة العمل عن بعد',
                'cons' => 'تعليم ذاتي فقط',
            ],

            // idx=88 — T2 (explicit: "We worked remotely")
            [
                'company' => 'T2 Business Research and Development',
                'role_title' => 'Software Development Trainee',
                'department' => 'Software Development',
                'city' => null,
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'remote',
                'stipend_sar' => 1000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 2,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'Job name: Software Development Trainee. Department: Software Development (there was an option to join the Operations department but I chose development). Every trainee is assigned to one or two mentors from the beginning of the training. The mentors were actual software developers working in the company so they are very experienced. After two months, the trainees were divided to teams and worked together to develop and deploy a complete web system. The company provides really good quality training, and two of my colleagues (both are female) were employed by the company afterwards, so there is a high chance of getting employed after you complete the training with them. We worked remotely.',
                'pros' => 'Strong mentorship, real project, hiring opportunity',
                'cons' => 'Small end-of-training bonus only',
            ],

            // idx=89 — Aramco Jeddah (explicit: physical at Jeddah branch)
            [
                'company' => 'ارامكو - جده - فرع بريمان',
                'role_title' => 'Information Security Analyst',
                'department' => 'Information Security',
                'city' => 'جدة',
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3500,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 3,
                'rating_culture' => 5,
                'rating_compensation' => 5,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'تدربت في قسم information security analysis في WRDD. المشرف كان متعاون جدًا ونمى فيني مهارات كثيرة وأعطاني نصائح قيمة. الأشياء اللي لاحظ أن عندي فيها نقطة ضعف أجبرني أن أسويها عشان أتعلم منها. اشتغلت على مشروع IT optimizations وكنت أسوي أغلب الأشياء وأعطي تقارير للمشرف. لا أنصح كثيرًا بالتدريب في هذا القسم لأنه ما كان عندهم خطة واضحة للتدريب. اللي يتدربون بنفس القسم لازم يكونون عندهم مهارات التواصل لأنه لو ما رحت كلمتهم ما يعطونك شي.',
                'pros' => 'مشرف داعم، مكافأة ممتازة',
                'cons' => 'لا توجد خطة واضحة',
            ],

            // idx=90 — Hudhud (explicit: "التواصل عن بعد ما كان عائق")
            [
                'company' => 'شركة هدهد (Hudhud Conversational AI)',
                'role_title' => 'Machine Learning Engineer',
                'department' => 'Product Engineering',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'remote',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'المسمى الوظيفي: Machine Learning Engineer. تدربت في صيف 2020، كانت الشركة في بداياتها صار لها سنة وكم شهر. كنت في قسم ال Product Engineering. الشركة تبني Customer Service ChatBot باللغة العربية، فكان شغلي تطوير أحد أجزاء تعلم الآلة في الـchatbot، وبالتحديد معالجة لغات طبيعية NLP. الشركة كانت صغيرة وقتها لكن مشرفي كان ممتاز جدًا والتواصل عن بعد ما كان عائق لأنهم يستخدمون وسائل التواصل وتنظيم المهام بفعالية. اتعلمت كثيرًا في المجال، وكمية الشغل مناسبة لفترة التدريب، وفريق العمل ممتاز من ناحية علمية وتوجيهية.',
                'pros' => 'مشرف ممتاز، تعلم عميق في NLP، تواصل فعال',
                'cons' => 'بدون مكافأة',
            ],

            // idx=99 — SDAIA (explicit: "مكاتبهم جنب بعض" — physical mixed offices)
            [
                'company' => 'سدايا',
                'role_title' => 'متدرب حوسبة سحابية',
                'department' => 'إدارة الحوسبة السحابية',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 3,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'اشتغلت في إدارة الحوسبة السحابية في قسم إدارة الخدمات. تجربتي معهم بشكل عام أقيمها ٥٠٪. عادية جدًا، دخلت بحماس كبير وانصدمت بالواقع. طوال فترة تدريبي كانت تجيني تاسك إلى ٢ تاسك بالأسبوع وأقدر أخلص التاسك الواحد بساعة أو ساعتين. لكن التاسك نفسها للأمانة تعجبني وفي مجالي، خلوني أشتغل على نظامهم وأخذ داتا حقيقية وأحللها. الموظفون محترمون وما حصلت منهم شيء يضايق. البيئة مختلطة من الدرجة الأولى، الرجال والبنات مكاتبهم جنب بعض ما فيه فصل.',
                'pros' => 'موظفون محترمون، داتا حقيقية',
                'cons' => 'فراغ معظم الوقت',
            ],

            // idx=101 — Aramco (explicit: Jeddah physical)
            [
                'company' => 'ارامكو السعودية',
                'role_title' => 'متدرب',
                'department' => 'منع الخسائر',
                'city' => 'جدة',
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3500,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 5,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت في قسم منع الخسائر بجدة. القسم أبدًا مو IT وكنت لوحدي فيه بس أعطوني تاسكات نوعًا ما ناسبت مجالي، اشتغلت على تاسكات تسهل طريقة شغلهم وشيء يستفيدون منه. كانوا متعاونين جدًا وتعلمت منهم كثيرًا. ضروري تثبتون لهم أنكم شغيلين ومو جايين للاسم بس عشان يعطونكم شغل.',
                'pros' => 'فريق متعاون، مكافأة ممتازة',
                'cons' => 'القسم ليس تقني',
            ],

            // idx=102 — KFMC (explicit: "يوجد تدريب حضوري بالرياض")
            [
                'company' => 'King Fahad Medical City',
                'role_title' => 'متدرب',
                'department' => 'تقنية المعلومات',
                'city' => 'الرياض',
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'hybrid',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'متدربة، قسم تقنية المعلومات، متدربات بنفس جامعتي، تصميم ويب سايت باستخدام لغة سي شارب و SQL Server Management Studio. يوجد تدريب حضوري بالرياض وتدريب عن بعد. أنصح فيه وبشدة، التدريب متعة وفائدة أكثر مما أنه متطلب.',
                'pros' => 'مرن بين حضوري وعن بعد، متعة وفائدة',
                'cons' => null,
            ],

            // idx=109 — KACST Data (explicit: "ساعات الدوام مرنة جدًا ولا يوجد بصمة" — physical)
            [
                'company' => 'مدينة الملك عبدالعزيز للعلوم والتقنية - كاكست',
                'role_title' => 'متدرب علم بيانات',
                'department' => 'علم البيانات والذكاء الاصطناعي',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت في قسم علم البيانات والذكاء الاصطناعي، اشتغلت مع مشرفتي على مشروع كمبيوتر ڤجن. كنت المتدربة الوحيدة مع مشرفتي فكان الوضع مرن وكانت تسألني إذا أبي تعطيني لكتشرز ولا بس أشتغل، واخترت لكتشرز وكانت مفيدة جدًا. البيئة غير مختلطة إلى حد كبير، ساعات الدوام مرنة جدًا ولا يوجد بصمة أو أي طريقة تحضير.',
                'pros' => 'مشرفة داعمة، محاضرات مفيدة، دوام مرن',
                'cons' => 'بدون مكافأة',
            ],

            // idx=110 — SDAIA (explicit: "ممكن تحتاج تداوم كم يوم ف أماكن مختلفة" physical)
            [
                'company' => 'سدايا',
                'role_title' => 'متدرب',
                'department' => 'قسم الدراسات',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'مكان التدريب: قسم الدراسات. التدريب كان متنوع ويعطونك من الشغل والمشاريع اللي يشتغلون عليها وأغلبها مع شركات عالمية. اشتغلت على إدارة المشاريع وتحليل الأعمال وتحليل البيانات. كل متدرب راح يكون مسؤول عنه موظف واحد وراح تشتغلون في تيمات مختلفة. المتدربون لازم يحضرون اجتماعات القسم ويشاركون فيها. بناء على طبيعة عمل المشرف ممكن تحتاج تداوم كم يوم في أماكن مختلفة زي توكلنا أو أي جهات تابعة لسدايا. بيئة العمل مريحة على الرغم من أنها مختلطة وكل متدرب له مكتب خاص. ساعات عمل مرنة، الجميع خلوقون وسلسون. خذوا التدريب في آخر مستوى بدون مواد.',
                'pros' => 'مشاريع عالمية، مكتب خاص، دوام مرن',
                'cons' => 'بدون مكافأة',
            ],

            // idx=116 — Tahakom (explicit: "من كثر الزحمة يحطون بنات في اماكن العيال" physical)
            [
                'company' => 'تحكم',
                'role_title' => 'Test Engineer',
                'department' => 'Testing',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 2000,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 3,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت ك Test Engineer تحت مسمى Coop trainee. أول كم أسبوع ما كان فيه شغل بعدين بدينا ندخل في مشاريع الشركة. التدريب كان ممتازًا لأنك تشتغل كموظف وتيم التيستنق رهيبون ومتعاونون جدًا. بالنسبة للاختلاط يعتمد على مكان مكتبك أحيانًا من كثر الزحمة يحطون بنات في أماكن العيال.',
                'pros' => 'تيم ممتاز، شغل كموظف، مشاريع حقيقية',
                'cons' => 'بطء البداية',
            ],

            // idx=125 — CMA (explicit: "مكاتب البنات منفصله عن مكاتب الرجال" physical)
            [
                'company' => 'هيئه السوق الماليه',
                'role_title' => 'متدرب أمن معلومات',
                'department' => 'إدارة أمن المعلومات',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => 2000,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 3,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت بقسم إدارة أمن المعلومات تحتها فريقين GRC و SOC. بـ GRC تدربت على كتابة السياسات ومراجعة سياسات تتعلق بالأمن السيبراني داخل الهيئة وخارجها. بالنسبة لـ SOC اشتغلت معاهم شغل حقيقي من ناحية spam and phishing and email release. مهام SOC كانت حلوة لأنك تشتغل شغل حقيقي عكس GRC اللي كله سياسات. في SOC رح تتدرب وتستفيد بشكل كبير. مكاتب البنات منفصلة عن مكاتب الرجال، وقت الاجتماع فيها اختلاط.',
                'pros' => 'شغل حقيقي في SOC، مكافأة جيدة',
                'cons' => 'GRC نظري بحت',
            ],

            // idx=130 — MEWA (explicit: "مكاتب البنات لهم قسم مكاتب خاص مقفل")
            [
                'company' => 'MEWA | وزارة البيئة والمياه والزراعة',
                'role_title' => 'متدرب حوكمة تقنية المعلومات',
                'department' => 'حوكمة تقنية المعلومات',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت بقسم حوكمة تقنية المعلومات. اشتغلنا على مشروع CMMI وISO أكثر من فئة، وعطوني مهام تحليل للسياسات والإجراءات بإدارة تقنية المعلومات والتحول الرقمي، وعطوني بوزشنز تقنية أسوي لها وصف وظيفي. بيئة العمل مرة حلوة. المكاتب ما هي مختلطة، البنات لهم قسم مكاتب خاص مقفل، بس عموم الاجتماعات مختلطة.',
                'pros' => 'مشاريع CMMI وISO حقيقية، بيئة حلوة',
                'cons' => 'بدون مكافأة',
            ],

            // idx=132 — Leen (explicit: "المكان في الرقمية" physical + "موفره نقل ترددي (باصات)")
            [
                'company' => 'لين لخدمات الاعمال',
                'role_title' => 'ML Engineer',
                'department' => 'Data',
                'city' => 'الرياض',
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'ML Engineer - Data department. تيم مكون من ٥-٦ أشخاص، نصهم سينير ونصهم توهم متوظفين. التدريب ٦ أشهر وعرضوا علي تمديد للـIntern. دخلت معهم بالشغل مباشرة ويعتمدون على شغل المتدربين على طول. خفيفين دم وإذا سألتيهم يجاوبون. المكان في الرقمية، المواقف سيئة بس لين موفرة نقل ترددي (باصات) من يووك أو ذا زون. المكان كبير وكويس والأغلب الموجودون في لين صغار. التوظيف على حسب توفر البوزشن. المتدربون الكووب على وقتي ما يعطونهم أجهزة وهذه كانت المشكلة الرئيسية. المكان كويس بشكل عام وممتاز للي يحتاج intern.',
                'pros' => 'شغل حقيقي مباشر، نقل ترددي، فرصة توظيف',
                'cons' => 'ما يعطون أجهزة للمتدربين',
            ],

            // idx=139 — Devoteam (explicit: "الدوام يكون بمقر الكلاينت")
            [
                'company' => 'Devoteam',
                'role_title' => 'Data Engineer',
                'department' => 'Data',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'Data Engineer. تدريبي عبارة عن برنامج يمتد لـ 6 أشهر فيه أهداف لازم أحققها من شهادات أو أسايمنتس معينة. اشتغلت كمهندس بيانات، بالبداية كان لازم أجتاز بعض الدورات المتعلقة بالبرمجة وحوكمة البيانات، بعدها دخلت مشروع يركز على الذكاء الاصطناعي والبيانات الضخمة. اشتغلت على جودة البيانات على برنامج Informatica وأيضًا ETL و data cleansing and profiling والبرمجة بلغة SQL وبايثون. البيئة جدًا متساعدة وخبراتهم عالية. كونها شركة استشارية، الدوام يكون بمقر الكلاينت.',
                'pros' => 'برنامج منظم، شهادات، خبرات عالية',
                'cons' => 'الدوام بمقر الكلاينت (متنقل)',
            ],

            // idx=146 — Tahakom (explicit: "البيئة جيدة" + "فعاليات المقامة بالمقر")
            [
                'company' => 'تحكم (المسؤولة عن نظام ساهر)',
                'role_title' => 'Intern Software Developer',
                'department' => 'الذكاء الاصطناعي / تطوير الحلول',
                'city' => null,
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 2000,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 3,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'قسمين: الذكاء الاصطناعي — عطوني مشروع اختباري لفكرة، يسمحون بالأكسس على السوبر كومبيوتر حقهم وهناك ملفات إرشادية لاستخدامه. مشرفي المباشر صعب التعامل معه شوي وعدم مراعي لكوني جديدة على نظامهم. لكن تعلمت الكثير، لديهم كل أسبوعين تقريبًا سشن لنقل الخبرات. قسم تطوير الحلول — بمسمى intern software developer، فرونت إند باستخدام Angular. مشرفتي المباشرة كانت رائعة، دربتنا على مشروع خارجي ثم دخلتنا مشروع فعلي. تستخدم Git على fork, Bitbucket. البيئة جيدة، الكل يحب التعرف على المتدربين، فعاليات المقامة بالمقر جميلة وتجدد الطاقات. يطولون على إصدار شهادة إتمام التدريب، وتأخير بعرض الوظيفة.',
                'pros' => 'وصول إلى سوبر كومبيوتر، مشاريع فعلية، فعاليات',
                'cons' => 'مشرف صعب في قسم AI، تأخير في الشهادات والعروض',
            ],

            // idx=150 — TCC (explicit: "المكان أغلبه رجال والمكتب متلاصقه")
            [
                'company' => 'TCC (Technology Control Co.)',
                'role_title' => 'Coop Trainee',
                'department' => 'Security Services',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 4,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'المسمى كان "COOP". تسوي خطة تدريب مع مشرفك هناك وتقسم الخطة على الأقسام. اشتغلت بقسم Security Services، كان شهر مع GRC وشهر مع DFIR. الشركة ما فيها متدربون كثير لأن التدريب فقط ترشيح داخلي. الشركة شبه حكومية ومملوكة لتحكم الاستثمارية التابعة لصندوق الاستثمار السعودي، وشغالة على أنظمة مثل نفاذ. ما كانوا يمسكوني شغل حقيقي غالبًا لكن كان زي التاسك هم قبل اشتغلوها ويراجعون معي شغلي. المكان أغلبه رجال والمكاتب متلاصقة، لكن في مكاتب منعزلة نسائية.',
                'pros' => 'خطة مرنة بين GRC وDFIR، مكافأة جيدة، فرصة توظيف',
                'cons' => 'قلة الشغل الحقيقي',
            ],

            // idx=151 — Alinma Bank (explicit: "مختلطة ولكن فيه مكاتب مغلقة مخصصة للنساء")
            [
                'company' => 'بنك الانماء',
                'role_title' => 'متدرب تعاوني',
                'department' => 'Shared Services',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 1,
                'rating_learning' => 1,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 2,
                'recommendation' => 'no',
                'review_text' => 'ما فيه مسمى تدريبي، تدربت في قسم shared services. ما كان فيه مهام التدريب بس برزنتيشن ومهام بسيطة جدًا SQL query. ما أعطونا أجهزة عشان نبدأ نتدرب معهم. ما أنصح في التدريب معهم إلا لو كنتوا تعرفون المشرف اللي بيمسكك. تجربتي ما كانت جيدة، التدريب في الجامعة متأكدة أنه بيكون أفضل. مختلطة ولكن فيه مكاتب مغلقة مخصصة للنساء.',
                'pros' => 'اسم البنك',
                'cons' => 'لا مهام، لا أجهزة، لا خطة',
            ],

            // idx=155 — PwC (explicit: "الشغل دائمًا حسب العميل" — on-client onsite)
            [
                'company' => 'PwC',
                'role_title' => 'متدرب استشارات تقنية',
                'department' => 'Technology Consulting',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 4000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 5,
                'rating_culture' => 4,
                'rating_compensation' => 5,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'مسماي الوظيفي: متدرب استشارات تقنية. القسم هو استشارات، المجال حسب المشروع اللي تنحط فيه، للأسف ما تقدر تختار، لكن الحل تبني علاقات مع مدراء تحبذ أن تشتغل معهم. كنت حريصة أن أشتغل في مشاريع إدارة واستراتيجية البيانات، فاضطريت أغير مشروعي مرتين. غالبًا كل مشروع راح يكون فيه فريق من ٣-٦ أشخاص وتايم لاين المشروع ممكن يكون ٣ شهور أو أجل غير مسمى. فرص التعلم كبيرة سواء في المجال التقني أو على المستوى الشخصي. الشغل دائمًا حسب العميل وحسب الفريق، بيئة الشركة ممتازة لكن يبقى ٥٠٪ من التجربة بناء على العميل.',
                'pros' => 'فرص تعلم واسعة، exposure عالي',
                'cons' => 'التجربة تتفاوت بحسب العميل والمدير',
            ],

            // idx=158 — Nuzum Alkhibrat (explicit: "كان هناك نساء الشركة لكن في قسم خاص")
            [
                'company' => 'شركة نظم الخبرات لتقنية المعلومات',
                'role_title' => 'متدرب سايبر',
                'department' => 'السايبر',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 1,
                'rating_learning' => 1,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 1,
                'recommendation' => 'no',
                'review_text' => 'كنت متدرب في قسم السايبر. صراحة التدريب كان تسليكي جدًا، حتى الخطة اللي كتبوها ما مشوا عليها. كان ٩٩٪ من شغلي بور بوينت وورد وإكسل، فالخبرة المكتسبة قليلة جدًا بالنسبة لمجال السايبر. إذا تبي فائدة من التدريب فما أنصحك تتدرب. كان هناك نساء الشركة لكن في قسم خاص.',
                'pros' => null,
                'cons' => 'تدريب تسليكي، الخطة لم تُنفذ',
            ],

            // idx=160 — SABIC (explicit: "بيئة مختلطه لكن مكاتب البنات بجهه والعيال بجهه")
            [
                'company' => 'سابك',
                'role_title' => 'Business Analyst',
                'department' => 'Business Application',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3500,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 5,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'تدربت في قسم Business Application بمسمى بزنس اناليست واشتغلت على مشروع خاص بسابك. كانت تجربة جميلة وتفرق التجربة على حسب المنجر اللي بيكون مشرفك. بيئة مختلطة لكن مكاتب البنات بجهة والعيال بجهة، يعني ما في مكتب بنت وولد جنب بعض.',
                'pros' => 'مشروع حقيقي، مكافأة ممتازة',
                'cons' => 'التجربة تتفاوت حسب المدير',
            ],

            // idx=161 — Alkaraj (explicit: "البيئة مختلطة في الاجتماعات غالبا ولكن المكاتب معزولة")
            [
                'company' => 'الكراج',
                'role_title' => 'محلل أعمال',
                'department' => 'تحليل الأعمال',
                'city' => null,
                'duration_months' => 3,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 4,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'اشتغلت بقسم تحليل الأعمال. الصراحة البيئة تقنية حلوة وأشوفها ممتازة لخريجين الحاسب. يعتمد على مشرفك إذا حاب يعلمك أو لا. نصيحتي إذا حسيت المشرف مو قاعد يعطيك شغل حاول تكلم المسؤول أو الليدر أن تبي تغير المشرف. برضو فيه أقسام كثيرة مثل تصميم الواجهات وتطوير الجوال والتطبيقات. البيئة مختلطة في الاجتماعات غالبًا ولكن المكاتب معزولة.',
                'pros' => 'أقسام تقنية متنوعة',
                'cons' => 'بدون مكافأة، يعتمد على المشرف',
            ],

            // idx=165 — STC Operations (explicit: "البيئة مختلطة ولكن يوجد ladies section")
            [
                'company' => 'STC',
                'role_title' => 'متدرب System Operations',
                'department' => 'System Operations - Digital Applications',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'System operations - digital applications. المسمى الوظيفي يختلف بحسب المهام لكل شخص بالقسم. التيم جدًا متساعد ويعطيك وقته وجهده عشان تتعلم، لكن يبغى لك تسعين وراهم يعني ما راح ينادونك هم، أنتي تروحين لهم وبيعطونك اللي تبين. الآكسس على الأنظمة ما يجي بالساهل. الخبرة جدًا قوية هنا، لو طلعتي وأنتي عارفة كل شيء بتكون خبرتك واو لأن هذا المجال في هذه الشركة مرة deep مو زي بقية الشركات. أشوفه مكان مثالي للتدرب فيه. البيئة مختلطة ولكن يوجد ladies section.',
                'pros' => 'خبرة عميقة، فريق داعم',
                'cons' => 'تحتاج متابعة ذاتية',
            ],

            // idx=166 — EY (explicit: "بتشتغلون في مكان العميل")
            [
                'company' => 'EY',
                'role_title' => 'Technology Consultant Intern',
                'department' => 'Technology Consulting',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 4000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 5,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'Technology consultant intern. التيم والمشاريع تختلف على حسب الجهة لأن بتشتغلون في مكان العميل. بالنسبة للشغل يختلف من مشروع لمشروع بس ترا الكونسلتنق يدخل فيه بزنس مرة كثير يعني بتستفيدون. البيئة مرة تساعد أنكم تتعلمون، الكل يبي يساعدك ويعلمك، وعندهم شهادات ودورات تتوفر لكم مجانًا من منصة Udemy. بتكتسبين خبرة كبيرة لأن بتشتغلون في أكثر من مشروع. عندهم برنامج تدريبي للخريجين احتمال كبير تدخلون فيه.',
                'pros' => 'شهادات Udemy مجانية، مشاريع متنوعة، برنامج خريجين',
                'cons' => null,
            ],

            // idx=171 — Tahakom (explicit: "المبنى 7 أدوار دورين منها للنساء")
            [
                'company' => 'تحكم للتحكم التقني والأمني الشامل TAHAKOM',
                'role_title' => 'متدرب تطوير تطبيقات',
                'department' => 'تطوير البرمجيات - التطبيقات',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 2000,
                'mixed_env' => false,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 3,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'تدربت في قسم تطوير البرمجيات وتحديدًا التطبيقات. التدريب مفيد جدًا وكانوا منظمين. الكل متعاون ولطيف جدًا، يدخلونكم الاجتماعات ويعطونكم شغل حقيقي. البيئة جميلة جدًا من مبنى وموظفات وطبيعة عمل. المبنى 7 أدوار، دورين منها للنساء ومنفصلة تمامًا يعني عادي تفصخين العباية.',
                'pros' => 'منظمين، شغل حقيقي، بيئة نسائية متكاملة',
                'cons' => null,
            ],

            // idx=173 — Elm (explicit: "البيئه مختلطه لكن المكتب منفصله" physical)
            [
                'company' => 'شركة علم',
                'role_title' => 'مهندس اختبار جودة البرمجيات',
                'department' => 'قطاع الحلول الرقمية - QA',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'تدربت كمهندس اختبار جودة البرمجيات تحت قطاع الحلول الرقمية. وقعت عقدي بالبداية على تدريب 4 أشهر وهي أقل مدة تسمح فيها علم، بعدها مددت التدريب لـ 6 أشهر. التيم معي مرة بطل، كان الكل يحاول يساعدني عشان أتعلم. المشاريع اللي مسكتها كبيرة منها الضمان الاجتماعي المطور ورابطة العالم الإسلامي. عاملوني معاملة موظف وبعض الحاجات مسكتها وكنت مسؤولة عنها لوحدي. أقدر أقول إني لميت كل شغل QA خلال مدة التدريب. الحمد لله بعد التدريب جاني عرض وظيفي منهم. البيئة مختلطة لكن المكاتب منفصلة، فيه أقسام نسائية متكاملة ما تحتاج تلبس العباية.',
                'pros' => 'معاملة موظف، مشاريع كبيرة حقيقية، عرض وظيفي',
                'cons' => null,
            ],

            // idx=177 — Erada (explicit: "الدوام الرسمي من 8 إلى 2" + physical offices)
            [
                'company' => 'مجمع ارادة للصحة النفسية',
                'role_title' => 'متدرب حاسب',
                'department' => 'الحاسبات',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 3,
                'rating_culture' => 4,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'رحت لقسم التدريب في مستشفى الملك خالد، تم توجيهي إلى مجمع إرادة للصحة النفسية. معي ثلاثة طلاب من كليتي واستقبلنا مشرف قسم الحاسبات في المجمع. المشرف يعطينا مهام تشمل فحص أجهزة الحاسب، نشيك على دومين كل الأجهزة ونعدلها إذا تحتاج تعديل، ومهام أخرى مثل استقبال مشكلات الموظفين، وتثبيت وتحديث البرامج، وتعديل أنظمة الحماية. الدوام الرسمي من 8 إلى 2، لكن المشرف كان يتساهل معنا. راح تحتك مع الموظفين كثير مثل الدكاترة والإدارة وتدخل على مكاتبهم وأجهزتهم وتعدل عليها.',
                'pros' => 'مشرف متساهل، احتكاك مباشر مع المستخدمين',
                'cons' => 'مهام لا تتعلق بالتخصص بالكامل',
            ],

            // idx=179 — Qabas (explicit: "كنا المتدربات البنات مع بعض بغرفه")
            [
                'company' => 'شركة قبس التقنية - Qabas tech',
                'role_title' => 'Cybersecurity Specialist',
                'department' => 'Cybersecurity',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 2,
                'rating_learning' => 1,
                'rating_culture' => 2,
                'rating_compensation' => 1,
                'overall_rating' => 2,
                'recommendation' => 'no',
                'review_text' => 'الشركة كانت آخر حل لي قبل يقفل قبول فرص التدريب، وهي شركة صغيرة تقنية يشتغلون على مواقع ومعسكرات تقنية. قالت لي المشرفة إني سايبر سيكيورتي سبيشلست بس الشغل كان كله دوكيومنت، ما اشتغلت على تولز أو شي فعليًا سايبر. الحضور والانصراف ما يدققون فيه. عرضوا علي فرصة تمهير بس رفضتها لأن ما عندهم شغل سايبر. حسيت أني ما تعلمت أو استفدت شي. كنا المتدربات البنات مع بعض بغرفة فيها مكاتب بس الغرف الثانية فيها رجال والمكتب حقنا قزاز. مافيه غرفة صلاة أو غرفة راحة للبنات، فاللي منقبة ممكن يطفشها هذا الشيء.',
                'pros' => 'حضور مرن',
                'cons' => 'لا شغل حقيقي، لا غرفة صلاة/راحة',
            ],

            // idx=188 — Al-Sultan (explicit: "فصلونا عن الرجال" + physical)
            [
                'company' => 'شركة السلطان القابضة بالقنفذة',
                'role_title' => 'متدرب تسويق/تطوير موقع',
                'department' => 'التسويق',
                'city' => 'القنفذة',
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 3,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'كنت في فريق التسويق، اشتغلنا معهم طول الفترة في أغلب أعمالهم وقمنا بشكل خاص بإنشاء موقع للشركة وتحديثه بما يناسب من متطلبات. التيم كان متعاون جدًا والمشرفة كانت مهتمة بتعليمنا. هم مقسمون أنفسهم هناك على المهام وعندهم خبرة كبيرة في التسويق. البيئة مختلطة في العمل ولكن كنا بنات اللي نتدرب ففصلونا عن الرجال. التدريب فوق الممتاز وكانوا موفرين سبل الراحة ومهتمين جدًا بنا، بس ما ناسب تخصصي لأني كمبيوتر ساينس. اكتسبنا خبرة كبيرة صراحة.',
                'pros' => 'مشرفة داعمة، خبرة تسويقية',
                'cons' => 'لا يناسب تخصص الحاسب بالكامل',
            ],

            // idx=192 — DSShield (explicit: "مقر الشركة في الرياض")
            [
                'company' => 'DSShield',
                'role_title' => 'Project Coordinator',
                'department' => 'PMO',
                'city' => 'الرياض',
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'المسمى الوظيفي project coordinator، تدربت في قسم PMO. التيم كان متعاون جدًا وخبراتهم ممتازة. اشتغلت على مشاريع كثيرة ومريت على جميع مراحل المشاريع بدايته ونهايته، في النص تعرفت على المشاكل اللي ممكن تحصل وكيف ممكن تنحل. مقر الشركة في الرياض.',
                'pros' => 'تيم متعاون، تغطية دورة مشاريع كاملة',
                'cons' => 'بدون مكافأة',
            ],

            // idx=203 — KACST HCI (explicit: "تتطلب سكن ومواصلات" — physical Riyadh)
            [
                'company' => 'King Abdulaziz city for science and technology',
                'role_title' => 'أخصائي تفاعل الإنسان مع الحاسب',
                'department' => 'معهد أبحاث الأمن السيبراني',
                'city' => 'الرياض',
                'duration_months' => 4,
                'sector' => 'government',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'أخصائي تفاعل الإنسان مع الحاسب. تدربت في معهد أبحاث الأمن السيبراني مع تيم دكتورة أثير. اشتغلت على مشروعين ومسكت الواجهات فيهم وتجربة المستخدم. جهة التدريب رهيبة جدًا، أنصح بها الكل. لكنها في الرياض وتتطلب سكن ومواصلات ولا يوجد أي تعاون من المدينة من هذه الناحية.',
                'pros' => 'تيم بحثي ممتاز، مشاريع على واجهات المستخدم',
                'cons' => 'لا تعاون في السكن والمواصلات',
            ],

            // idx=205 — Leen (explicit: "المكان في الرقمية" previously, here says onsite work)
            [
                'company' => 'لين لخدمات الاعمال',
                'role_title' => 'Data Analyst',
                'department' => 'Advanced Analytics',
                'city' => null,
                'duration_months' => 6,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 5,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'كنت في قسم البيانات، advanced analytics. الشغل عبارة عن SQL، إما تحليل بيانات أو الأقسام الداخلية أو جهات خارجية طالبين بيانات، تعديلات على داشبورد أو تسوي واحد من الصفر. بعد التدريب التعاوني ما في توظيف ولكن يعرضون GDP (المكافأة أكثر ولكن مو راتب ولا منتهي بتوظيف ولكن ممكن تتوظف). بالنسبة لقسم البيانات البيئة جدًا مريحة والكل متعاون مع المتدربين لأن أصلًا أغلب المتوظفين كانوا coop أو gdp. ويعطون المتدرب شغل حقيقي فحتى لو ما تتوظف عندهم رح تطلع بخبرة.',
                'pros' => 'بيئة مريحة، شغل حقيقي، مسار GDP',
                'cons' => 'لا توظيف مباشر بعد COOP',
            ],

            // idx=209 — SITE (explicit: "فيه مكاتب نسائية فقط للي ماتبي اختلاط")
            [
                'company' => 'سايت site',
                'role_title' => 'COOP',
                'department' => 'إداري',
                'city' => null,
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => 3000,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 4,
                'rating_learning' => 4,
                'rating_culture' => 5,
                'rating_compensation' => 4,
                'overall_rating' => 4,
                'recommendation' => 'yes',
                'review_text' => 'المسمى: coop. القسم إداري. التجربة عمومًا رائعة ويعاملونك كموظف إلا شويتين. للأخوات اللي ما تبي اختلاط فيه مكاتب نسائية فقط.',
                'pros' => 'معاملة كموظف، مكاتب نسائية متوفرة',
                'cons' => null,
            ],

            // idx=211 — CAMCO (explicit: "المكان اللي يداومون فيه IT كئيب جدا" physical)
            [
                'company' => 'CAMCO - شركة مترو العاصمة',
                'role_title' => 'IT Trainee',
                'department' => 'IT',
                'city' => 'الرياض',
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'onsite',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => false,
                'rating_mentorship' => 1,
                'rating_learning' => 1,
                'rating_culture' => 1,
                'rating_compensation' => 1,
                'overall_rating' => 1,
                'recommendation' => 'no',
                'review_text' => 'المسمى الوظيفي IT Trainee. القسم IT. التيم اللي معي 11 موظف في قسم IT، المدير والـSeniors كلهم أجانب، الباقون سعوديون وأغلبهم جديدون في الشركة. مشاريع اشتغلت عليها: صفر. ما راح تستفيد شي عندهم، إذا بغيت شي من Senior كل واحد يرميك على الثاني. المكان اللي يداومون فيه IT كئيب جدًا. إذا بس تبي تخلص التدريب التعاوني قدم عليهم، لكن إذا تبي فائدة دور جهة ثانية.',
                'pros' => null,
                'cons' => 'صفر مشاريع، فريق غير متعاون، مكان كئيب',
            ],

            // idx=214 — Ejada (explicit: "كان فيه اختيار أني أداوم ريموتلي" — hybrid)
            [
                'company' => 'إجادة للنظم - Ejada Systems',
                'role_title' => 'AI Trainee',
                'department' => 'AI Delivery Department',
                'city' => 'الرياض',
                'duration_months' => 4,
                'sector' => 'private',
                'modality' => 'hybrid',
                'stipend_sar' => null,
                'mixed_env' => true,
                'job_offer' => true,
                'rating_mentorship' => 4,
                'rating_learning' => 5,
                'rating_culture' => 5,
                'rating_compensation' => 1,
                'overall_rating' => 5,
                'recommendation' => 'yes',
                'review_text' => 'AI Trainee - AI Delivery Department. تجربة ممتازة من كل النواحي. قدرت أشتغل وأجرب على أكثر من شي في كم مجال. كنت المتدربة الوحيدة ولما عدوا أول يومين بدون شغل رحت كلمت أحد الموظفين أن يكون مينتور لي، وكلم المانجر حقي ومن بعدها صار شغلي كله معه. ساعدني هذا الشيء كثير. غالب مدة التدريب اشتغلت في product management في أحد المشاريع. قدرت أشتغل على أحد المشاريع اللي موجودة في القسم رغم أنه تبع IoT sector موب AI. الدوام كان مرن جدًا لكن مهم أنك تكون متواجد لما يكون عندك شغل، وكان فيه اختيار أني أداوم ريموتلي وهذا شي مرة زين. أغلب الموظفين صغار وجديدين ولسه خبراتهم بسيطة، الاجتماعات والتواصل يعتمد 90٪ على Teams والإيميل.',
                'pros' => 'مرونة بين حضوري وريموت، تعلم متعدد المجالات',
                'cons' => 'معظم الموظفين جدد الخبرة',
            ],

            // idx=215 — T2 (explicit: "التدريب كله كان اونلاين بس نداوم بالمقر" — hybrid)
            [
                'company' => 'T2',
                'role_title' => 'متدرب أمن سيبراني',
                'department' => 'الأمن السيبراني',
                'city' => null,
                'duration_months' => 2,
                'sector' => 'private',
                'modality' => 'hybrid',
                'stipend_sar' => null,
                'mixed_env' => false,
                'job_offer' => false,
                'rating_mentorship' => 3,
                'rating_learning' => 3,
                'rating_culture' => 3,
                'rating_compensation' => 1,
                'overall_rating' => 3,
                'recommendation' => 'maybe',
                'review_text' => 'تدريبي كان في قسم الأمن السيبراني. بداية كان عبارة عن GRC وبعدها دخلنا على Wazuh لين نهاية التدريب، كان في خطة له. التدريب كله كان أونلاين بس نداوم بالمقر، هذا الشيء ما حبيته. كان فيه دورات إضافية عن قسم البيانات و GRC و SOC. كنا نشتغل على أشياء وهمية مو حقيقي، وكل نهاية أسبوع نستعرض إيش سوينا مع المشرف.',
                'pros' => 'تغطية GRC/SOC/Wazuh، دورات إضافية',
                'cons' => 'أشياء وهمية، الدوام بالمقر رغم أن المحتوى أونلاين',
            ],
        ];
    }
}
